### ISSUE TITLE
Process Killed Suddenly

### ISSUE THREAD

**Issue by WinnieLaugh** [divamgupta/deep_clustering_kingdra#2]
Hi,

I was trying the code with "python run_exp.py configs/kingdra_ladder_im_mnist.json" and the program always abruptly stopped with only the message "killed" at the end of the output.

Do you know how to solve this?

Thanks a lot in advance.

Best

**Comment by divamgupta** [comment]
This killed message is probably the OS killing the process due to high
resource use.
After what output do you see before the killed message?

**Comment by WinnieLaugh** [comment]
`2020-11-24 20:18:25.069 Epoch 5/5

2020-11-24 20:18:25.069 - 24s - loss: 5.9945

2020-11-24 20:22:28.106 /bin/bash: line 27: 318 Killed sh start.sh`

This is the output of the server. I tried on my own desktop and it showed almost the same thing.

By the way, is it natural that GPU is used for a very small portion of the time while the CPU is always occupied?

Best,

**Comment by WinnieLaugh** [comment]
Hi,

I don't know why, but when I started another training job to fight for resources with this training, the weird "killed" just went away, at least for now.

The training might slow down, but this seems an easy work around.

Thanks for your help!

Best,

**Comment by divamgupta** [comment]
You need a lot of CPU host memory for this code. I was able to run this code fine on a server with a ram of 256GB. 
Maybe increasing the swap space could fix this.

**Comment by WinnieLaugh** [comment]
No wonder it always ends with the "killed" message, the CPU memory demand is really high.

Thanks for your information. 

Best,
