### ISSUE TITLE
final clusters

### ISSUE THREAD

**Issue by stronglily** [divamgupta/deep_clustering_kingdra#4]
Will the final clusters cover the entire dataset？Will each data sample be assigned a pseudo label?   I try to use your clustering method to experiment on the dataset used for my research problem.  There are 16 categories in my experimental dataset,  just over a thousand samples from nine categories were selected for labeling after 50 epoch. Could you please give me some help?

**Comment by divamgupta** [comment]
The final clusters returned should cover the entire dataset.
Every data sample might not be assigned a pseudo label.

Is there any way to reproduce your issue on a smaller scale?

**Comment by stronglily** [comment]
Do I have too many categories in my dataset?   Will more than 10 categories damage the clustering results?

**Comment by divamgupta** [comment]
Yes having more number of clusters might damage the performance. You can
try the hyper parameters of the 20 news dataset.

**Comment by stronglily** [comment]
Thank you for your patient reply. I will try again.
